### PR TITLE
Ability to pre-set dice results when rolling

### PR DESCRIPTION
**Pull request by Nedomas**
Implements the ability to pre-set dice results instead of generating random numbers on roll.

This is useful if you do the randomness somewhere else (for example - server).

A simple example would be:
```jsx
import React, { Component } from 'react'
import ReactDice from 'react-dice-complete'
import 'react-dice-complete/dist/react-dice-complete.css'

export default class Dices extends Component {
  componentDidUpdate() {
    const dices = [5, 3]
    this.reactDice.rollAll(dices)
  }

  render() {
    return (
        <ReactDice
          numDice={2}
          rollDone={() => {}}
          ref={dice => this.reactDice = dice}
        />
    )
  }
}
```

### CODE REVIEW

**Comment by kali67** [comment]
Is it possible to merge this in? I would really like to use this feature.

**Comment by Nedomas** [comment]
@AdamTyler could you merge and release this one?

**Comment by kali67** [comment]
@AdamTyler, are you able to merge and release this please?
Thanks.

**Comment by AdamTyler** [comment]
@kali @Nedomas I plan to revisit and revive this repo in the next few days. Will keep you posted

**Pull request closed without merging**
